### ISSUE TITLE
Invalid tag blocks all the subsequent tags from import

### ISSUE THREAD

**Issue by weltling** [FriendsOfPHP/pickleweb#39]
The way to reproduce:
- in the extension imported into pickleweb, create and push tag test-tag-42
- the github log says, pickleweb responded with exception containing: Invalid version string "test-tag-42"
- create and push a valid tag, like 3.2.1
- the github log says, pickleweb responded with 
  {"status":"error","message":"weltling\/imagick-3.2.1 error on import:Invalid version string \"test-tag-42\""}

Any subsequent tag will have similar error message, no exception thrown.

**Comment by weltling** [comment]
In addition, if an extension already contains test-tag-42 before, the import fails with the message

An error occurred while retrieving extension data. Please veriry your tag and try again later.Invalid version string "test-tag-42"

**Comment by pierrejoye** [comment]
Why should it accept this tag?

See the semver tag naming.

Or do you mean it fails if _any_ tag has a bad name?

It should raise a warning in the log for any of them and fails for the one
triggering the push.

**Comment by weltling** [comment]
Yeah, if there's only one bad tag, it'll fail to import anything. Or if it already imported, creating one bad tag will block any subsequent tags added (just by the flow described).

**Comment by pierrejoye** [comment]
Thanks for the catch!

I fix the uncaught exception.

I am adding now a note about the pushed tag must be valid as other tags are not changed anyway, we bail out. Keeping in mind that the creation of deletion of tags will trigger the hook, we would have caught any other changes already.

The import simply reparse everything instead of fetching the info for the new tag and merge to the existing stored tags. It is simply easier to do it this way.
